# To use:
#
#   $ conda env create -f environment.yml
#   $ conda activate gcs
#
name: gcs
channels:
  - defaults
  - conda-forge
dependencies:
  - autopep8=1.6.0
  - build=0.7.0
  - matplotlib=3.5.1
  - numpy=1.21.5
  - pandas=1.4.1
  - pip=21.2.4
  - pylint=2.12.2
  - pytest=7.1.2
  - python=3.9.12
  - scipy=1.7.3
  - sphinx=5.0.2
  - twine=4.0.2
  - pip:
    - numpy-stl==2.17.1
    - numpydoc==1.5.0
    - bentley-ottmann==7.3.0
    - pytest-cov==4.1.0
    - sphinx-rtd-theme==1.2.2
