# Environment for ReadTheDocs.
# The minimum requirements to run gcs and build documentation.
#
name: gcs-rtd
channels:
  - conda-forge
dependencies:
  - conda-forge::pip=21.2.4
  - conda-forge::python=3.9.12
dependencies:
  - pip:
    - bentley-ottmann==7.3.0
    - mapbox_earcut==1.0.0
    - numpy==1.21.5
    - numpydoc==1.5.0
    - numpy-stl==2.17.1
    - pandas==1.4.1
    - scipy==1.7.3
    - sphinx==5.0.2
    - sphinx-rtd-theme==1.2.2
